# Generated by Django 3.2.13 on 2022-11-21 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_info_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infocomment',
            name='grade',
        ),
    ]
