# Generated by Django 3.2.13 on 2022-10-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_imgae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imgae',
            new_name='image',
        ),
    ]
