# Generated by Django 3.2.13 on 2022-11-21 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='talk_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
