# Generated by Django 3.2.13 on 2022-11-21 08:42

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0002_community_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='media/'),
        ),
    ]
