# Generated by Django 3.2.13 on 2022-11-21 09:48

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0003_community_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='media/'),
        ),
    ]
