# Generated by Django 3.2.13 on 2022-11-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0004_alter_community_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
